#!/bin/bash

source data.sh
cp example_"$RESOURCE".yaml $DEST

sed -i "s/PROVIDER/$PROVIDER_NAME/g" $DEST

sed -i "s^SHOWBACK_RULE^$CP_SHOWBACK_RULE_NAME^g" $DEST
sed -i "s^KIND^$CP_SHOWBACK_RULE_KIND^g" $DEST
sed -i "s^TYPE^$CP_SHOWBACK_RULE_TYPE^g" $DEST
sed -i "s^PRICE^$CP_SHOWBACK_RULE_PRICE^g" $DEST
sed -i "s^GLOBAL_ALERT^$CP_SHOWBACK_RULE_GLOBAL_LIMIT^g" $DEST
sed -i "s^PROJECT_ALERT^$CP_SHOWBACK_RULE_PROJECT_LIMIT^g" $DEST
sed -i "s^ORGANIZATION_REF^$CP_SHOWBACK_RULE_ORG^g" $DEST
sed -i "s^SHOWBACK_CREDENTIAL^$CP_SHOWBACK_RULE_CREDS^g" $DEST
