#!/bin/bash

source data.sh
cp example_"$RESOURCE".yaml $DEST

sed -i "s/PROJECT_NAME/$CP_PROJECT_NAME/g" $DEST
sed -i "s/CLOUD_REF/$CP_PROJECT_CLOUD_CREDS/g" $DEST
sed -i "s/ORGANIZATION_REF/$CP_PROJECT_ORG/g" $DEST
sed -i "s/QDISK_SIZE/$CP_PROJECT_QDISK/g" $DEST
sed -i "s/QRAM_SIZE/$CP_PROJECT_QRAM/g" $DEST
sed -i "s/KP_REF/$CP_PROJECT_KP/g" $DEST
#sed -i "s/BACK_REF/$CP_PROJECT_BACK/g" $DEST
sed -i "s/PROJECT_FLAVOR/$CP_PROJECT_FLAVOR/g" $DEST
sed -i "s/IMG/$CP_PROJECT_IMG/g" $DEST
sed -i "s/VM_FLAVOR/$CP_PROJECT_VM_FLAVOR/g" $DEST
sed -i "s/VM_IMAGE_ID/$CP_PROJECT_VM_IMG_ID/g" $DEST
sed -i "s/VM_NAME/$CP_PROJECT_VM_NAME/g" $DEST
sed -i "s/VM_SA/$CP_PROJECT_VM_SA/g" $DEST
sed -i "s/VM_VOLUME_SIZE/$CP_PROJECT_VM_VOL_SIZE/g" $DEST
sed -i "s/VM_USER/$CP_PROJECT_VM_USER/g" $DEST
