#!/bin/bash

source data.sh
cp example_"$RESOURCE".yaml $DEST

sed -i "s/PROVIDER/$PROVIDER_NAME/g" $DEST

sed -i "s^KUBECONFIG^$CP_KUBECONFIG_NAME^g" $DEST
sed -i "s^SCOPE^$CP_KUBECONFIG_SCOPE^g" $DEST
sed -i "s^ROLE^$CP_KUBECONFIG_ROLE^g" $DEST
sed -i "s^PROJECT^$CP_KUBECONFIG_PROJECT^g" $DEST
sed -i "s^NAMESPACE^$CP_KUBECONFIG_NAMESPACE^g" $DEST
sed -i "s^USER^$CP_KUBECONFIG_USER^g" $DEST
sed -i "s^VALIDITY^$CP_KUBECONFIG_VALIDITY^g" $DEST
