apiVersion: backupcredential.taikun.jet.crossplane.io/v1alpha1
kind: Credential
metadata:
  name: BACKUP_CREDENTIAL
spec:
  forProvider:
    name: "BACKUP_CREDENTIAL"
    s3AccessKeyId: ACCESS_KEY_ID
    s3Endpoint: ENDPOINT
    s3Region: REGION
    s3SecretAccessKey: SECRET_KEY
  providerConfigRef:
    name: default
