name: CI

on:
  push:
    tags:
      - v*
    branches:
      - main
      - release-*
  pull_request: {}
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: "1.19"
  GOLANGCI_VERSION: "v1.31"
  DOCKER_BUILDX_VERSION: "v0.4.2"
jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: General Setup
        run: |
          sudo apt-get update && \
          sudo apt-get install -yy -q --no-install-recommends \
          build-essential \
          ca-certificates \
          curl \
          git \
          jq \
          lsb-release \
          make \
          wget \
          sudo && \
          sudo apt-get update && \
          sudo apt-get upgrade -y && \
          sudo apt-get autoremove -y && \
          sudo apt remove --autoremove golang && \
          sudo apt-get clean
      - name: Docker Install
        run: |
          sudo apt install runc
          sudo apt install containerd
          sudo apt-get install docker.io -y
          sudo snap install docker
          sudo systemctl status docker
      - name: Go Set up
        run: |
          sudo apt-get update  
          sudo apt-get -y upgrade
          sudo rm -rvf /usr/local/go
          wget  https://go.dev/dl/go1.19.linux-amd64.tar.gz
          sudo tar -xvf go1.19.linux-amd64.tar.gz
          sudo cp go/bin/go /usr/bin/
          sudo mv go /usr/local
      - name: Build provider's images
        run: |
          go version
          sudo go version
          git clone https://github.com/itera-io/provider-jet-taikun.git
          cd provider-jet-taikun
          make submodules
          sudo make all
      - name: Lint
        run: |
          make lint

  detect-noop:
    runs-on: ubuntu-18.04
    needs: build-and-lint
    outputs:
      noop: ${{ steps.noop.outputs.should_skip }}
    steps:
      - name: Detect No-op Changes
        id: noop
        uses: fkirc/skip-duplicate-actions@v2.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          paths_ignore: '["**.md", "**.png", "**.jpg"]'
          do_not_skip: '["workflow_dispatch", "schedule", "push"]'
