name: Docker Image CI

on:
  release:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: General Setup
        run: |
          sudo apt-get update && \
          sudo apt-get install -yy -q --no-install-recommends \
          build-essential \
          ca-certificates \
          curl \
          docker.io \
          git \
          jq \
          lsb-release \
          make \
          sudo && \
          sudo apt-get update && \
          sudo apt-get upgrade -y && \
          sudo apt-get autoremove -y && \
          sudo apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
      -
        name: Go Set up
        run: |
          GO_VERSION=1.17.5 && \
          GO_HASH=bd78114b0d441b029c8fe0341f4910370925a4d270a6a590668840675b0c653e && \
          curl -fsSL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz -o golang.tar.gz && \
          echo "${GO_HASH}  golang.tar.gz" | sha256sum -c - && \
          tar -C /usr/local -xzf golang.tar.gz && \
          rm golang.tar.gz
          PATH /usr/local/go/bin:$PATH
      -
        name: Build provider's images
        run: |
          git clone https://github.com/nivraph/provider-jet-taikun.git
          cd provider-jet-taikun
          make submodules
          make build
          
      -
        name: Push provider's images
        run: |
          docker images | cat
          
          
        
